properties([parameters([[$class: 'ChoiceParameter', choiceType: 'PT_SINGLE_SELECT', description: 'Please provide the environment to be built', filterLength: 1, filterable: false, name: 'environment', randomName: 'choice-parameter-5815454297916', script: [$class: 'GroovyScript', fallbackScript: [classpath: [], sandbox: true, script: 'return["error"]'], script: [classpath: [], sandbox: true, script: 'return ["dev", "qa", "stage", "prod"]']]], [$class: 'ChoiceParameter', choiceType: 'PT_SINGLE_SELECT', description: 'Please provide the service to be built', filterLength: 1, filterable: false, name: 'service_pipeline', randomName: 'choice-parameter-5815459629388', script: [$class: 'GroovyScript', fallbackScript: [classpath: [], sandbox: true, script: 'return ["error"]'], script: [classpath: [], sandbox: true, script: 'return ["Onboarding", "BO", "Cards", "IB", "IMS"]']]], [$class: 'DynamicReferenceParameter', choiceType: 'ET_FORMATTED_HTML', description: 'Node on which service needs to be copied', name: 'node', omitValueField: false, randomName: 'choice-parameter-5815475026485', referencedParameters: 'environment', script: [$class: 'GroovyScript', fallbackScript: [classpath: [], sandbox: false, script: 'return "error"'], script: [classpath: [], sandbox: true, script: '''if(environment.equals("dev")){
     return "$DEV_NODE<input type=\\"hidden\\" name=\\"value\\" value=\\"$DEV_NODE\\" />";
}else if(environment.equals("qa")){
      return "$QA_NODE<input type=\\"hidden\\" name=\\"value\\" value=\\"$QA_NODE\\" />";
}else if(environment.equals("stage")){
      return "$STAGE_NODE<input type=\\"hidden\\" name=\\"value\\" value=\\"$STAGE_NODE\\" />";
}else if(environment.equals("prod")){
	  return "$STAGE_NODE<input type=\\"hidden\\" name=\\"value\\" value=\\"$STAGE_NODE\\" />";
}''']]]])])
